name: "Puppet"
description: "Turn dashboards into nice pictures with optimized e-ink rendering"
version: "1.20.0"
slug: "puppet"
homeassistant_api: true
init: false
arch:
  - aarch64
  - amd64
ports:
  10000/tcp: 10000
options:
  access_token: ""
  keep_browser_open: false
schema:
  access_token: str
  keep_browser_open: bool
